services:
  - type: web
    name: gestor-tareas
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /opt/render/project/src/tareas.db
